name: Sync to business repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo personal
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Push to business repo
        env:
          BUSINESS_REPO_TOKEN: ${{ secrets.BUSINESS_REPO_TOKEN }}
        run: |
          git config --global user.name "Jsoza1"
          git config --global user.email "jsoza993@gmail.com"

          git remote remove business || true
          git remote add business https://x-access-token:${BUSINESS_REPO_TOKEN}@github.com/SozaSystems/web-electricista.git

          # Push SIN workflows
          git push business main --force -- ':!.github/workflows/*'
