name: Sincronizar a Espejo

on:
  push:
    branches:
      - main

jobs:
  build:
    # ESTA ES LA L√çNEA CLAVE
    if: github.repository == 'Jsoza1/web-electricista'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Push to mirror
        env:
          BUSINESS_REPO_TOKEN: ${{ secrets.BUSINESS_REPO_TOKEN }}
        run: |
          git config --global user.name "Jsoza1"
          git config --global user.email "jsoza993@gmail.com"
          
          # Eliminar workflows localmente para no sobreescribir configuraciones si fuera necesario
          rm -rf .github/workflows
          
          git remote add business https://x-access-token:${BUSINESS_REPO_TOKEN}@github.com/SozaSystems/web-electricista.git
          git push business main --force
